USE [master]
GO

/****** Object:  Database [assignment3darshil]    Script Date: 2024-03-29 10:12:06 PM ******/
CREATE DATABASE [assignment3darshil]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'assignment3darshil', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS19\MSSQL\DATA\assignment3darshil.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'assignment3darshil_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS19\MSSQL\DATA\assignment3darshil_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [assignment3darshil].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [assignment3darshil] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [assignment3darshil] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [assignment3darshil] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [assignment3darshil] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [assignment3darshil] SET ARITHABORT OFF 
GO

ALTER DATABASE [assignment3darshil] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [assignment3darshil] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [assignment3darshil] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [assignment3darshil] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [assignment3darshil] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [assignment3darshil] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [assignment3darshil] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [assignment3darshil] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [assignment3darshil] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [assignment3darshil] SET  DISABLE_BROKER 
GO

ALTER DATABASE [assignment3darshil] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [assignment3darshil] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [assignment3darshil] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [assignment3darshil] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [assignment3darshil] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [assignment3darshil] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [assignment3darshil] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [assignment3darshil] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [assignment3darshil] SET  MULTI_USER 
GO

ALTER DATABASE [assignment3darshil] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [assignment3darshil] SET DB_CHAINING OFF 
GO

ALTER DATABASE [assignment3darshil] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [assignment3darshil] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [assignment3darshil] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [assignment3darshil] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [assignment3darshil] SET QUERY_STORE = ON
GO

ALTER DATABASE [assignment3darshil] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [assignment3darshil] SET  READ_WRITE 
GO

